[versions]
gradleVersion = "8.1.4"
kotlinVersion = "1.9.10"

dokkaVersion = "1.9.10"
appcompatVersion = "1.6.1"
espressoVersion = "3.5.1"

junitVersion = "4.13.2"
junitExtVersion = "1.1.5"
multidexVersion = "2.0.1"
materialVersion = "1.10.0"
activityComposeVersion = "1.8.0"
composeMaterialVersion = "1.3.1"
composeCompilerVersion = "1.5.3"

androidxComposeBom = "2023.10.01"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }

com-google-android-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
androidx-activity-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }

androidx-test-espresso-espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoVersion" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-ui-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

junit-junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExtVersion" }

androidx-multidex-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidexVersion" }
org-jetbrains-dokka-kotlinAsJavaPlugin = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokkaVersion" }
